name: 🤔 Question
description: Ask a question about the project
title: "[Question]: "
labels: ["question"]
assignees:
  - WantedChef

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help!

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation & Setup
        - Configuration
        - Usage & Commands
        - Features & Functionality
        - Troubleshooting
        - Development & Contributing
        - API & Integration
        - Performance & Optimization
        - Security
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context or background information
      placeholder: What are you trying to accomplish?

  - type: textarea
    id: tried
    attributes:
      label: What Have You Tried?
      description: What have you already tried to solve this?
      placeholder: |
        - Checked the documentation
        - Searched existing issues
        - Tried...

  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you using?
      placeholder: e.g., 2.2.0

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Screenshots, code snippets, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have checked the documentation
          required: true
        - label: I have searched existing issues for similar questions
          required: true
